# This is a basic workflow to help you get started with Actions

name: Fetch Appointments

# Controls when the workflow will run
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '* * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        id: curl
        run: |
          content=$(curl -L "https://burghquayregistrationoffice.inis.gov.ie/Website/AMSREG/AMSRegWeb.nsf/(getAppsNear)?readform&cat=All&sbcat=All&typ=New&k=55FE1105EF583BA6372E52F4B0A15EDE&p=EFDC4F4EEA43EB71562785A6240DF4DF&_=1638960440089")
          currentDate=`date`
          echo '::set-output name=data::'$content
          echo '::set-output name=date::'$currentDate
      - uses: gr2m/write-csv-file-action@v1.x
        with:
          path: data.csv
          columns: fetch_datetime, result
          "fetch_datetime": ${{ steps.curl.outputs.date }}
          "result": ${{ steps.curl.outputs.data }}
      # push updated file back to main branch
      - run: git config --local user.email "action@github.com"
      - run: git config --local user.name "GitHub Action"
      - run: git commit -am "data.csv updated"
      - run: "git push https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
